### ISSUE TITLE
BlockPixel Resource pack causes: java.lang.RuntimeException: Can't parse xml at: minecolonies:gui/citizen/windowinteraction.xml when interacting with MineColonies entities

### ISSUE THREAD

**Issue by kedamono** [ldtteam/BlockUI#71] opened 2023-12-02 16:13 UTC
BlockUI version: blockui-1.20.1-1.0.125-BETA
Any MineColonies version for 1.20.1, though repro'ed in minecolonies-1.20.1-1.1.333-BETA
BlockPixel version: BlockPixel-JavaEdition_13

Disclaimer: Ray told me to post this bug in BlockUI as I couldn't find a place to file it for BlockPixel in hopes you could figure out what's going on.

Issue: When I try to interact with a citizen, the game crashes and I get the following error:

```
The game crashed whilst unexpected error
Error: java.lang.RuntimeException: Can't parse xml at: minecolonies:gui/citizen/windowinteraction.xml

Exit Code: 255
```

This also occurs if I try to use the clipboard, or access the Tasks tab in a hut block.

Steps to reproduce:

1. Install MineColonies 1.20.1, most recent version. Install the BlockPixel resource pack and activate it in the Resource Pack menu of Minecraft.
2. Create a new world and colony and allow citizens to spawn. 
3. Right click a citizen to interact with them.

Expected: The Citizen's UI appears and you can interact with that.

Actual Result: The game freezes, then crashes to desktop with the above error message.

Crash Log:
[https://gist.github.com/kedamono/e495a7917409da07f449f70f50e0d93d](https://gist.github.com/kedamono/e495a7917409da07f449f70f50e0d93d)
Latest Log:
https://gist.github.com/kedamono/e5b60d62702ac4390a05841009a4c776[
](https://gist.github.com/kedamono/e5b60d62702ac4390a05841009a4c776)

**Comment by Raycoms** [comment] 2023-12-02 16:33
Can you tell us the blockpixel version you are using?

**Comment by Nightenom** [comment] 2023-12-02 16:48
This is caused by some out-of-jar texture having malformed .mcmeta json: `malformed JSON at line 5 column 4 path $.texture`, unfortunately we don't log the path of crashing texture, weird enough this shouldn't crash at all, ~~please leave this open till PR fixing this behavior gets merged~~

**Comment by Nightenom** [comment] 2023-12-02 17:30
@kedamono Should no longer crash with latest blockui, please report with logs so we can investigate further, the log should contain message starting with `Parsing sprite metadata failed for:`

**Comment by kedamono** [comment] 2023-12-02 18:44
Thanks Nightenom! I'll keep an eye out for this in the logs.

**Closed as completed** 2023-12-22 14:01 UTC
